default: &default

test:
  <<: *default
  infinum_azure:
    client_id: 'vault_client_id'
    client_secret: 'vault_client_secret'
    tenant: 'infinumtest'
    users_auth_url: 'http://example_api_url_with_users.com'
