AllCops:
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Lambda:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/*.rb'
